[package]
name = "inventory"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
rdkafka = { version = "0.36", features = ["ssl-vendored"] }
serde = { version = "1.0", features = ["derive"] }
surrealdb = "1.5.1"